### PR TITLE
revised test runner and generator

### LINKED ISSUE #8: clean up output, and consider own output generator
This issue consists of two closely-related parts. Firstly, the test output is excessively noisy:

```javascript

> pelias-acceptance-tests@0.0.0 test /home/sevko/src/mapzen/acceptance-tests
> mocha -R spec tests



  GET /search

    1) [id:0] query: { input: 'brooklyn' } (top 3)

    2) [id:1] query: { input: 'brooklyn, ny' } (top 3)

    3) [id:2] query: { input: 'new york' } (top 3)

    4) [id:3] query: { input: 'philadelphia' } (top 3)

    5) [id:4] query: { input: 'new york, ny' } (top 3)

    6) [id:5] query: { input: '130 dean street brooklyn, ny' } (top 1)

    ✓ [id:6] query: { input: 'billerica' } (top 1) (54ms)

    ✓ [id:7] query: { input: 'billerica, ma' } (top 1) (90ms)

    7) [id:8] query: { input: '15 call street billerica, ma' } (top 1)

    8) [id:9] query: { input: 'union sq' } (top 3)

    9) [id:10] query: { input: 'union square' } (top 1)

    ✓ [id:11] query: { input: 'portland' } (top 1) (59ms)

    ✓ [id:12] query: { input: 'paris' } (top 1) (73ms)

    10) [id:13] query: { input: 'france' } (top 3)

    11) [id:14] query: { input: 'prospect park' } (top 1)

    ✓ [id:15] query: { input: 'london' } (top 1) (57ms)


  5 passing (7s)
  11 failing

  1) GET /search [id:0] query: { input: 'brooklyn' } (top 3):
     Error: timeout of 2000ms exceeded
      at null.<anonymous> (/home/sevko/src/mapzen/acceptance-tests/node_modules/mocha/lib/runnable.js:159:19)
      at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

  2) GET /search [id:1] query: { input: 'brooklyn, ny' } (top 3):
     Error: Expected result not in top 3
      at Object.<anonymous> (/home/sevko/src/mapzen/acceptance-tests/tests/searchTest.js:81:19)
      at Test.assert (/home/sevko/src/mapzen/acceptance-tests/node_modules/supertest/lib/test.js:221:6)
      at assert (/home/sevko/src/mapzen/acceptance-tests/node_modules/supertest/lib/test.js:132:12)
      at /home/sevko/src/mapzen/acceptance-tests/node_modules/supertest/lib/test.js:129:5
      at Test.Request.callback (/home/sevko/src/mapzen/acceptance-tests/node_modules/supertest/node_modules/superagent/lib/node/index.js:746:30)
      at Test.<anonymous> (/home/sevko/src/mapzen/acceptance-tests/node_modules/supertest/node_modules/superagent/lib/node/index.js:135:10)
      at Test.emit (events.js:95:17)
      at IncomingMessage.<anonymous> (/home/sevko/src/mapzen/acceptance-tests/node_modules/supertest/node_modules/superagent/lib/node/index.js:938:12)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:943:16
      at process._tickCallback (node.js:419:13)

  3) GET /search [id:2] query: { input: 'new york' } (top 3):
     Error: Expected result not in top 3
      at Object.<anonymous> (/home/sevko/src/mapzen/acceptance-tests/tests/searchTest.js:81:19)
      at Test.assert (/home/sevko/src/mapzen/acceptance-tests/node_modules/supertest/lib/test.js:221:6)
      at assert (/home/sevko/src/mapzen/acceptance-tests/node_modules/supertest/lib/test.js:132:12)
      at /home/sevko/src/mapzen/acceptance-tests/node_modules/supertest/lib/test.js:129:5
      at Test.Request.callback (/home/sevko/src/mapzen/acceptance-tests/node_modules/supertest/node_modules/superagent/lib/node/index.js:746:30)
      at Test.<anonymous> (/home/sevko/src/mapzen/acceptance-tests/node_modules/supertest/node_modules/superagent/lib/node/index.js:135:10)
      at Test.emit (events.js:95:17)
      at IncomingMessage.<anonymous> (/home/sevko/src/mapzen/acceptance-tests/node_modules/supertest/node_modules/superagent/lib/node/index.js:938:12)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:943:16
      at process._tickCallback (node.js:419:13)

  4) GET /search [id:3] query: { input: 'philadelphia' } (top 3):
     Error: timeout of 2000ms exceeded
      at null.<anonymous> (/home/sevko/src/mapzen/acceptance-tests/node_modules/mocha/lib/runnable.js:159:19)
      at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

/* etc */
```

The stack traces at the end make it difficult to view the failing tests at the top of the output, and there's some additional text in those (like the time the query took) that might not be worth displaying. I think the traces should definitely go, and while we remove them, we should consider just writing our own output generator here instead of using **mocha**. Could look something like this:

```
✘ [id 9] 'brooklyn': timeout of 2000ms exceeded
✘ [id 9] 'new york, ny': not in top 10 results
✘ [id 9] 'new york, ny': not in top 10 results
✓ [id 10] 'union sq': no `out` object specified
✓ [id 10] 'union square'
```

I'm suggesting that since it'll give us fine-tuned control over the output format in the long run, and would remove auto-injected mocha text.

### PR DESCRIPTION
**Pull request by sevko**
Wrote a custom test-runner and output generator which prints less noisy output to the terminal and will allow us to, in the future, easily re-format output (into, say, an email) and gather statistics (like the number of passing/failing tests).

Closes #8.

### CODE REVIEW

File: test.js [hunk 1]
```diff
@@ -0,0 +1,204 @@
...
+      }
+    });
+  });
+}
+
+/**
+ * URLs for the various Pelias APIs out in the wild. Can be specified as a
+ * command-line argument (see `runTests()`).
+ */
+var PELIAS_ENDPOINTS = {
```
Comment (dianashk) [inline test.js]: these should live in a config file somewhere, and you should be able to specify a different url as well.

Comment (sevko) [inline test.js]: Could be `pelias-config`?

File: test.js [hunk 2]
```diff
@@ -0,0 +1,204 @@
...
+    )
+    .parse( process.argv );
+
+  var apiUrl;
+  if( commander.endpoint in PELIAS_ENDPOINTS ){
+    apiUrl = PELIAS_ENDPOINTS[ commander.endpoint ];
+  }
+  else {
+    console.error(
+      apiUrl, 'is not a recognized endpoint. Try:',
```
Comment (dianashk) [inline test.js]: apiUrl won't have a value in the else clause, since it gets assigned in the if.

Comment (sevko) [inline test.js]: Oh, good catch. Was meant to be `commander.endpoint`.

File: test.js (hunk 1 above)
Comment (dianashk) [inline test.js]: pelias-config is good

File: test.js [hunk 3]
```diff
@@ -0,0 +1,200 @@
...
+      pass: 0,
+      fail: 0,
+      placeholder: 0,
+      timeTaken: null,
+      name: testSuite.name
+    },
+    results: []
+  };
+
+  var startTime = new Date().getTime();
```
Comment (dianashk) [inline test.js]: should probably use microtime for this kind of stuff

Comment (sevko) [inline test.js]: It's not really a benchmark and added as somewhat of stat-sugar, so I'd opt for the simplicity of `new Date()`. Plus, it's not totally accurate because these tests get executed in parallel (meaning `startTime` gets initialized immediately, while the API processes results more or less sequentially and the time per suite gets compounded with the time the preceding suites took to execute), but that's another problem. I can change over to `microtime`, though I'm not sure if it matters here.

Should tests be made sequential?

**Comment by dianashk** [comment]
* I like the ouput_generator abstraction. Feels like a stream might be appropriate here?
 * `test.js` would be better having just the command line args and config processing and then pull the test suite execution code into a separate file.
 * delete searchTest.js since it's not being used anymore.

File: test.js (hunk 3 above)
Comment (dianashk) [inline test.js]: True, this isn't a benchmarking tool, but a lot of requests take less than a second so you would see 0.

I think running them all in parallel is the way to go. It would be useful to see each request's round-trip time, as a way to gauge which types of requests might take longer than others. Agreed that total time doesn't mean very much here, so I'd be fine with losing that altogether.

Comment (sevko) [inline test.js]: These are actually being recorded on a per-suite basis, not per-request, and 9 requests (the current size of `search.json`) end up taking something like 655ms, so milliseconds seems granular enough. Maybe let's ditch per-suite time and just get aggregate time for all suites? Per-suite times are misleading if we run in parallel, so I think we should lose them, but total time taken is still accurate.

**Comment by sevko** [comment]
Addressed points 2 and 3. Not sure if a stream makes sense since we gather all of the test-results and statistics (in order to compute things like total number of passing/failing tests) before passing them to the output generator(s). The side-effect is that you don't see anything until all tests run to completion. Think it's worth implementing? Keep in mind that it wouldn't work for something like generating an email, so we'd have separate interfaces for the terminal and, for example, email output generators.

**Comment by dianashk** [comment]
Agreed, it's not worth refactoring to streams for reasons listed.
 +1
